language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t $DOCKER_USERNAME/234project-backend  .
- docker push $DOCKER_USERNAME/234project-backend
- docker pull dto80/project234-frontend
script:
- docker-compose -H "$DOCKER_HOST" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.20.0
  - secure: UWCANeni5T+OM1zYQN2YNue/FglwAa46gnEcc3clk2EIqcKb1mde7YfmcEGw/RBI5zzG52uCpDk9aAeIFfHLtOM0vIKphBYueAkLUMQCHWLLrjII+cI6E1CB9hoY6YDCaKYwXvJvPjfIFnlp7ffOjqp2v+0idCO4e/ZrbZPNbGMrt1GDnHgFvr2sIca4Gn4SLIev/OYoGB13ceB7loJOdGadA/KUvuHjtKJcVeoF45sYlDyz6c5r+ik50csIB4U5fQg9RlVUzxLxSA4A+DXdx+YaqFZu4xTEBTurI8s9kQsQ/NCJrvewkfIyseGze5ByS2UTwbo1V3Pb9PDhczDnNs2Wd5RCNIaCYhJhEUHF3zilQc2udV9sWs66T+6VSXzPLzemiECoGmCzfyoclr+AbtTX5NbGApoqLqMmjz7+sVdWa40TsqEYi/U4J8TZ719mNS+n9oC9yP6SvnShLx8Zh1sqIGTSxaLHjhiDh2y5SC4kvSblR9u6GjwddItskonGGf1DJaa1MeJqbh2PSwadlHY1pZ7XikGs4W45Ur131W3Bo5F+Xms7bGDvp1zpgX3nDUPMryK02blp7ocz2clj0LopCxvWSq+/KFV4UXQRoYJHoNGBePhQDS3BY6qn/4sOmkjsy/1aMRZG0AJHHgCpd2J3c+mB7+hMO6hFtyy7hxI=
  - secure: WlVIYbBnwPvnAK+iquH5kjr6mgpgV/Crp6m/Ldrp8chNjG6zphXCKj/dL0GXj52x66T9FeRTQ1ZDzPKggYrXXyRjWkGMR903SmjQBYDUq9rz8pEzA4gFLaMJt7VxbR9xiq5FRZ27uD9f3edMl/R5APVzpy8KLGeiwI18Ktbyodupo/HgBAg8evAasRUAcQueQ903uSp4psEIKmkaahxPm0K2RttaXofxxYYPxVsYVT2tDZGMe4vCLslr/H3XGaEdpTaIrUMw8KwBfbHFCQ3K6KzKCO4x1+bwb2IPCdxMhfNujbqYrRZoRpJb8Qfdire3xaBn6tA0eAqBCc21JWiIwW1uQsZQyN0644q0GTpBYTtRFpuebMXSviSnDEwv7731+Hv5dereqVeKMQ9A5u1EO+6MpyKoLxdVr2mg7bbAFxdun8zHzKvQ21bAb+iserw8MKpIR8QIKCwhxttjYmogz/+wIfaFkYz+oBJNEMVIbyOF3RMhvOmRx/f8CMacfeVVbeUhxImfkLgYXgnxq3Tem7FrPV5n+MsA/2lMYeuz1G6d426dcR5t0/awaAkAevxMFxCU1RxqqyqTfHdR17vIe7ckb4d913lOnuz3JAAl9tCOaYSwOcwGGiHJ+Takgc7tCt14tqAOYBC+N15ugOMnZOXglkrwbYnFYmfzai2XRmQ=
  - secure: YLO82DDfLTN2DG+hZkNTo2lVD0qqGtGV+H/1R97hyHvdv/xQkl65zjfOOnTFAizkB9ZrFzoFB8JPUUkiOHCcZcx7i1+HQs3PBsoWJJQuPwH5fKACA1vrf4pPf/w8w4yDz/GibAnDZ1wp0J3JFZQG2sHiXDPR5wHqp/1uu5oJIj9ugg298THfeQJtdyheRqW4MP7UZ/p1Bnie1+n1K3XoRc2tOjE+Z4B1sch8FzZCpCgZsMJpzDa79lgLpd6Cw/3zlOnrYviSHgLOghbkT0joYX1vUmrO1l9PTnBBEy55u2akzt4gslGGObQ3H87Zy2ctkYgBUFhmnlTTSXdsOvIolxzNfa/sYn+gTcUeFuHOeogcvId/xsDvHGxOcO2QF4Q4bUsYWx7aSXjNoI2M8LaiDnDvpgG8a4PNqzCFV4OEnI6vPIX+jQVYUEVwYWyrqkWhngTY0IUcfV9SZpK//yRn9R9geKdGff3IJVOPl5EA21ecK7pA9htPSp+Qlchtg8exzRY2JZYh8obP4UNuGj/Y8s2w2dTmzhmRhBff9kWCWIq4sSSp0S7HEWK0bwMXD1WYNn8f4a0xcM4Sy4H4CiyIE3ICmMYRna5Zk6LGDKde9ufq5/NqCr25GCiMG6GPLi8vtbSstKUWAwW0LgbeQvcQR+HVRWe0JVdKWSn95c7XXvk=
