version: '3.3'
services:
  backend:
    image: dto80/234-lab11:latest
    ports:
     - "8090:8080"
    volumes:
     - type: bind
       source: /setting/setting.json
       target: /usr/share/nginx/html/assets
  frontend:
    image: dto80/project234-frontend
    ports:
     - "8091:80"
