version: '3.3'
services:
  backend:
    image: getgorok/234project-backend:latest
    ports:
     - "8090:8080"
  frontend:
    image: dto80/project234-frontend
    ports:
     - "8091:80"
    volumes:
     - type: bind
       source: ./setting
       target: /usr/share/nginx/html/assets
